services:
#    fs_core.example:
#        class: FS\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    fs_core.locale_listener:
        class: FS\CoreBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }
